### ISSUE TITLE
「Google Cloudで学ぶ生成AIアプリ開発入門」2.5.2 について

### ISSUE THREAD

**Issue by YasunariIguchi** [google-cloud-japan/sa-ml-workshop#54]
お世話になっております。
本を購入し、進めさせていただいております。

P49（2.5.2の最後）のコマンド「gcloud builds submit . --tag $REPO/test-app」を実行すると、
私の方では以下のようなエラーが表示されました。

```
AccessDeniedException: 403 {サービスアカウント} does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
```

こちら、私の方で以下のようにコマンドを打つと解決しました。
```
gcloud projects add-iam-policy-binding {プロジェクト ID} --member="serviceAccount:{サービスアカウント}" --role="roles/storage.objectViewer"
```

また、上記実行後にもうひとつ、以下のようなエラーが出ました。

```
denied: Permission "artifactregistry.repositories.uploadArtifacts" denied on resource "projects/{プロジェクト ID}/locations/asia-northeast1/repositories/container-image-repo" (or it may not exist)
```

こちらは以下で解決しました：
```
gcloud projects add-iam-policy-binding {プロジェクト ID} --member="{サービスアカウント}" --role="roles/artifactregistry.writer"
```

他の方でも同じようなエラーが出た場合に、参考になればと思います。
もしくは、より良い方法やご指摘があればいただければと思います。

こちらの本、非常にわかりやすく記載がされていて進めやすいと感じています。
また類似の本が出版されましたら購入を検討させていただきます。

**Comment by enakai00** [comment]
報告ありがとうございます。`gcloud artifacts repositories create` コマンドでリポジトリを作成した後、必要な権限が設定されるまで少し時間がかかっているようです。こちらで確認した所では、１〜２分ほど待ってから `gcloud builds submit` コマンドを実行すると、該当のエラーは発生しなくなりました。Google Cloud 側で発生している一時的な問題かどうかは不明ですが、念のため、１〜２分ほど待ってから次の作業に進むように、正誤表に記載しておきたいと思います。
